// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW99Qa-7LIYFPdFoxW3ENXz3hj93YJlOw',
    appId: '1:223816673529:android:ff4ecfcad0034a28f5da28',
    messagingSenderId: '223816673529',
    projectId: 'thingathon-162d7',
    storageBucket: 'thingathon-162d7.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV-g1crNLaa3dykm9sYSHx8yZV1-8E_Do',
    appId: '1:223816673529:web:a658630f2a105471f5da28',
    messagingSenderId: '223816673529',
    projectId: 'thingathon-162d7',
    authDomain: 'thingathon-162d7.firebaseapp.com',
    storageBucket: 'thingathon-162d7.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh9RUp2ivQiPyMSSwx2zfEKOcQraFqmpk',
    appId: '1:223816673529:ios:1160c13d2eb05826f5da28',
    messagingSenderId: '223816673529',
    projectId: 'thingathon-162d7',
    storageBucket: 'thingathon-162d7.appspot.com',
    androidClientId: '223816673529-pctoa5l0sr8bm3a9pik99lefe1svnjq4.apps.googleusercontent.com',
    iosClientId: '223816673529-p3im3kh3ote96f8fmj514m75g700j9b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingathon',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh9RUp2ivQiPyMSSwx2zfEKOcQraFqmpk',
    appId: '1:223816673529:ios:1160c13d2eb05826f5da28',
    messagingSenderId: '223816673529',
    projectId: 'thingathon-162d7',
    storageBucket: 'thingathon-162d7.appspot.com',
    androidClientId: '223816673529-pctoa5l0sr8bm3a9pik99lefe1svnjq4.apps.googleusercontent.com',
    iosClientId: '223816673529-p3im3kh3ote96f8fmj514m75g700j9b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.thingathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV-g1crNLaa3dykm9sYSHx8yZV1-8E_Do',
    appId: '1:223816673529:web:9e9f2618b5f1f0a5f5da28',
    messagingSenderId: '223816673529',
    projectId: 'thingathon-162d7',
    authDomain: 'thingathon-162d7.firebaseapp.com',
    storageBucket: 'thingathon-162d7.appspot.com',
  );

}