name: thingathon
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#--------------- PACKAGES ------------------#

dependencies:
  flutter:
    sdk: flutter

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^4.0.4
  camera: ^0.10.5+9
  permission_handler: ^11.3.0
  provider: ^6.1.2
  image: ^4.1.7
  path_provider: ^2.1.2
  gallery_saver: ^2.3.2
  path: ^1.9.0

  #Utility Packages
  flutter_native_splash: ^2.3.1


  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^2.29.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.7.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  dio: ^5.4.3+1
  table_calendar: ^3.1.1
  gallery_picker: ^0.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: 
    size: 500
  ios: true
  image_path: "assets/Thing-T-Logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/Thing-T-Logo.png"
    background_color: "
    theme_color: "
  windows:
    generate: true
    image_path: "assets/Thing-T-Logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/Thing-T-Logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/


